force-app/main/default/objects/MarvelAPIKeys__c/MarvelAPIKeys__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Chaves API Marvel</label>
</CustomObject>

force-app/main/default/objects/MarvelAPIKeys__c/fields/PrivateKey__c.field-meta.xml
<CustomField>
    <fullName>PrivateKey__c</fullName>
    <label>Private Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MarvelAPIKeys__c/fields/PublicKey__c.field-meta.xml
<CustomField>
    <fullName>PublicKey__c</fullName>
    <label>Public Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegracaoUtils.cls
public with sharing class IntegracaoUtils {

    static IntegracaoUtils instance = null;

    public static IntegracaoUtils getInstance() {
        if (instance == null) {
            instance = new IntegracaoUtils();
        }

        return instance;
    }

    public String getTimestamp() {
        return String.valueOf(System.now().getTime()/1000);
    }

    public String getPrivateKey() {
        return MarvelAPIKeys__c.getOrgDefaults().PrivateKey__c;
    }

    public String getPublicKey() {
        return MarvelAPIKeys__c.getOrgDefaults().PublicKey__c;
    }

    public String getHash() {
        return 
        EncodingUtil.convertToHex(
            Crypto.generateDigest(
                'MD5',
                Blob.valueOf(getTimestamp() + getPrivateKey() + getPublicKey())
            )
        );
    }
}